prelude file support poc
wix-playground/intellij pull request #51
Opened 2019-12-22 21:49 UTC by comchi

discussed in slack

2020-01-01 17:41 UTC, ittaiz commented
@liucijus @ZachiNachshon can this move forward?

2020-01-02 08:23 UTC, liucijus requested changes
Please format your changes according google code style: https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml

It would be great if you can explain your design decisions (like subscribing to prelude file changes, etc).

2020-01-02 08:23 UTC, liucijus commented on base/src/com/google/idea/blaze/base/lang/buildfile/search/ResolveUtil.java
> +        // if it is build file we should start looking from topmost level
Reducing duplication and simplifying expressions would make this block more readable. Examples of duplciation:
`(BuildFile) parent`, `topLevelScope ? element : null`

2020-01-02 08:23 UTC, liucijus commented on base/src/com/google/idea/blaze/base/prelude/PreludeManagerImpl.java
> +    if (projectRoot != null) {
Use short circuit style instead of deep nesting. Eg.:
```java
if (foo == null) {
  return;
}
```

2020-01-08 07:50 UTC, comchi commented
Thanks for review, sorry was on a long vacation. Will fix comments and describe solution later today.

2020-01-09 10:55 UTC, comchi commented on base/src/com/google/idea/blaze/base/lang/buildfile/search/ResolveUtil.java
> +        // if it is build file we should start looking from topmost level
Ok, I will refactor it. I wanted to change existing code as less as possible

2020-01-09 10:59 UTC, comchi commented on base/src/com/google/idea/blaze/base/prelude/PreludeManagerImpl.java
> +    if (projectRoot != null) {
Usually I prefer to have `single exist point`, but ok, thanks

2020-01-09 11:07 UTC, comchi commented
as for architecture, three main points: 
1. I subscribed to file updates because I wanted IDEA to catch up will changes in prelude file without the mandatory to `resync`
2. I added my `lookup` code to ResolveUtil since after extensive debugging session it looks like the singe hole that all `lookups` are using
3. I used `Manager` for maintaining state because it's the only way I found how to maintain singleton 

In general I had like two days (spend too much on other fruitless initiatives in this plugin :( ) for this and almost no previous experience with Intellij Plugins so I admit that it all could be terribly wrong :)

2020-01-09 11:10 UTC, comchi commented
I will change code to comply review (code style + warning) after workday

2020-01-09 19:38 UTC, comchi commented
@liucijus I fixed style and your notes.

2020-01-13 15:06 UTC, liucijus approved these changes

2020-01-13 16:37 UTC, ZachiNachshon approved these changes
LGTM

2020-01-13 16:48 UTC, comchi commented
that's pretty cool, thanks 
How to get it in idea plugin? :)

2020-01-14 06:55 UTC, merged

2020-01-14 06:57 UTC, liucijus commented
Merged, let's do some testing on our fork.

2020-01-14 07:12 UTC, ittaiz commented
Exciting!!!!!!!!!!!!!!